version: '3'
services:
  jodel_api:
    build: ./node-api
    links:
        - mongo_for_jodel
        - redis_for_jodel
    ports:
        - "8080:8080"
  mongo_for_jodel:
    image: mongo:latest
    ports:
        - "27017"
        - "27018"
  redis_for_jodel:
    image: redis:4-alpine
    ports:
        - "6379"